name: Daily Stock Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1-5"   # 07:00 WIB (00:00 UTC) Senin–Jumat

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSL_CA: ${{ secrets.DB_SSL_CA }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }

      - name: Print time
        run: |
          echo "UTC:" && date -u
          TZ=Asia/Jakarta date

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run batch updater (5 hari perdagangan)
        run: |
          python app/batch_update.py --period 5d --suffix .JK --max-tickers 0

      - name: Generate Daily Signals
        run: |
          python app/signals_daily.py --days 240 --max-tickers 0