name: Daily Stock Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1-5'  # 07:00 WIB (00:00 UTC) Senin-Jumat

jobs:
  update:
    runs-on: ubuntu-latest
    
    # --- BAGIAN YANG DIUBAH ADA DI SINI ---
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    # ------------------------------------
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run daily signal generation
        run: python app/signals_daily.py --days 240 --max-tickers 0
