name: Daily Stock Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"   # 07:00 WIB (UTC+7), Senin–Jumat

concurrency:
  group: daily-update
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      PGHOST:     ${{ secrets.DB_HOST }}     # contoh: uvxcpafymowxdhhgzvru.supabase.co
      PGPORT:     ${{ secrets.DB_PORT }}     # pastikan "6543" (PgBouncer)
      PGDATABASE: ${{ secrets.DB_NAME }}     # contoh: postgres
      PGUSER:     ${{ secrets.DB_USER }}     # contoh: postgres
      PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      LOG_LEVEL: "INFO"
      YF_SLEEP_MS: "150"
      YF_RETRIES: "3"


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          # pastikan requirements.txt minimal berisi:
          # pandas
          # yfinance
          # psycopg2-binary>=2.9.9

      - name: Sanity check DB (opsional)
        run: |
          python - <<'PY'
          import os, psycopg2
          dsn=os.environ['DATABASE_URL']
          with psycopg2.connect(dsn) as c:
              with c.cursor() as cur:
                  cur.execute("select current_user, current_date")
                  print("DB OK ->", cur.fetchone())
          PY

      - name: Run batch updater (meniru halaman UI)
        run: |
          python app/batch_update.py --period 1mo --suffix .JK --max-tickers 0
