# .github/workflows/daily-update.yml
name: Daily Stock Price Update

on:
  # Menjalankan workflow setiap hari pada pukul 00:00 UTC (sekitar jam 7 pagi WIB)
  schedule:
    - cron: '0 0 * * *' 
  # Bisa juga di-trigger manual
  workflow_dispatch:

jobs:
  run_daily_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Ganti dengan versi Python yang lo pakai
          
      - name: Install Dependencies
        # Asumsi dependencies lo ada di requirements.txt 
        # (termasuk streamlit, yfinance, mysql-connector-python, pandas)
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          
      # --- Langkah Utama: Menjalankan Script Update ---
      - name: Run Stock Price Batch Update
        env:
          # WAJIB MENAMBAHKAN DB_PORT DAN DB_NAME SESUAI PERMINTAAN db_utils.py
          DB_HOST: ${{ secrets.DB_HOST }} 
          DB_PORT: ${{ secrets.DB_PORT }} # <-- HARUS DITAMBAHKAN (misalnya: 3306)
          DB_NAME: ${{ secrets.DB_NAME }} # <-- HARUS DITAMBAHKAN (Nama Database lo)
          DB_USER: ${{ secrets.DB_USER }} 
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
          
        run: |
          echo "Memulai eksekusi batch_update.py..."
          # Menggunakan Solusi 2 yang lebih robust untuk Streamlit apps, 
          # agar bisa import package dengan benar: python -m [package].[module]
          export PYTHONPATH=$PYTHONPATH:./app
          python -m app.batch_update 
          echo "Eksekusi selesai."
