name: Daily Stock Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"   # 07:00 WIB (UTC+7), Senin–Jumat

concurrency:
  group: daily-update
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      # HARUS diset di repo Settings → Secrets and variables → Actions → New repository secret
      # Contoh Supabase: postgresql://postgres:<PASS>@<HOST>.supabase.co:6543/postgres?sslmode=require
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      YF_SLEEP_MS: "150"
      YF_RETRIES: "3"
      LOG_LEVEL: "INFO"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          # pastikan ada:
          # pandas
          # yfinance
          # psycopg2-binary>=2.9.9

      - name: Sanity check DB (opsional)
        run: |
          python - <<'PY'
          import os, psycopg2
          dsn=os.environ['DATABASE_URL']
          with psycopg2.connect(dsn) as c:
              with c.cursor() as cur:
                  cur.execute("select current_user, current_date")
                  print("DB OK ->", cur.fetchone())
          PY

      - name: Run batch updater (meniru halaman UI)
        run: |
          python app/batch_update.py --period 1mo --suffix .JK --max-tickers 0
