# .github/workflows/daily-update.yml
name: Daily Stock Price Update

on:
  # Menjalankan workflow setiap hari pada pukul 06:00 UTC (atau 13:00 WIB)
  # Untuk jam 6 pagi WIB (GMT+7), kita set jam 23:00 UTC di hari sebelumnya
  # Tapi karena lo minta setiap pagi, kita coba set 00:00 UTC (jam 7 pagi WIB)
  schedule:
    # '0 0 * * *' artinya pada menit 0, jam 0 (tengah malam UTC), setiap hari, setiap bulan, setiap hari dalam seminggu
    # Ini akan dieksekusi sekitar jam 7 pagi WIB (GMT+7)
    - cron: '0 0 * * *' 
  # Bisa juga di-trigger manual
  workflow_dispatch:

jobs:
  run_daily_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Ganti dengan versi Python yang lo pakai
          
      - name: Install Dependencies
        # Asumsi dependencies lo ada di requirements.txt (e.g., pandas, mysql-connector-python)
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          
      # --- Langkah Utama: Menjalankan Script Update ---
      # PENTING: Lo perlu database yang bisa diakses dari GitHub Actions, 
      # atau lo harus Mock/Simulasi akses DB-nya. 
      # Kalau lo pakai DB di Docker Compose, lo harus setup runner di tempat DB itu ada.
      # Untuk CI/CD simpel di Actions, lo bisa pakai Secrets.
      - name: Run Stock Price Batch Update
        env:
          # Variabel Environment yang Dibutuhkan Script Python
          DB_HOST: ${{ secrets.DB_HOST }} # Ganti dengan IP/Hostname DB eksternal lo
          DB_USER: ${{ secrets.DB_USER }} 
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
        run: |
          echo "Memulai eksekusi batch_update.py..."
          python app/batch_update.py # Ganti path ini kalau batch_update.py nggak ada di folder 'app'
          echo "Eksekusi selesai."
