name: Daily Stock Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"   # 07:00 WIB weekdays

concurrency:
  group: daily-update
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}   # wajib di-setup di repo Secrets
      YF_SLEEP_MS: "200"
      YF_RETRIES: "3"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure tickers file
        run: |
          if [ ! -f app/tickers.csv ]; then
            echo "symbol" > app/tickers.csv
            echo "BBRI"  >> app/tickers.csv
            echo "BMRI"  >> app/tickers.csv
            echo "BRIS"  >> app/tickers.csv
          fi

      - name: Sanity check DB
        run: |
          python - <<'PY'
          import os, psycopg2
          dsn=os.environ['DATABASE_URL']
          with psycopg2.connect(dsn) as c:
              with c.cursor() as cur:
                  cur.execute("select current_date")
                  print("DB OK")
          PY

      - name: Run batch updater (5 hari terakhir)
        run: |
          python app/batch_update.py --period 5d --suffix .JK --max-tickers 0 --tickers-csv app/tickers.csv
